# -*- coding: utf-8 -*-
"""welcome 5 py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UaaMCzFqnWf-9AlbIuDG_KcaqxsTwZ6_
"""

pip install faker

"""### Patient Risk Classification"""

# Define risk thresholds based on general medical guidelines (these are illustrative and can be adjusted)
def classify_risk(patient):
    risk_score = 0

    # Blood Pressure
    if patient['blood_pressure_systolic'] >= 140 or patient['blood_pressure_diastolic'] >= 90:
        risk_score += 2 # High BP
    elif patient['blood_pressure_systolic'] >= 120 or patient['blood_pressure_diastolic'] >= 80:
        risk_score += 1 # Elevated BP

    # Sugar Level
    if patient['sugar_level_mg_dL'] >= 126:
        risk_score += 2 # Diabetic
    elif patient['sugar_level_mg_dL'] >= 100:
        risk_score += 1 # Pre-diabetic

    # Cholesterol
    if patient['total_cholesterol_mg_dL'] >= 240 or patient['ldl_cholesterol_mg_dL'] >= 160 or patient['hdl_cholesterol_mg_dL'] < 40:
        risk_score += 2 # High cholesterol
    elif patient['total_cholesterol_mg_dL'] >= 200 or patient['ldl_cholesterol_mg_dL'] >= 130 or patient['hdl_cholesterol_mg_dL'] < 50:
        risk_score += 1 # Borderline high cholesterol

    # Heart Rate
    if patient['heart_rate_bpm'] < 60 or patient['heart_rate_bpm'] > 100:
        risk_score += 1 # Abnormal heart rate

    if risk_score >= 4:
        return 'High Risk'
    elif risk_score >= 2:
        return 'Medium Risk'
    else:
        return 'Low Risk'

# Apply the risk classification function to each patient record
df_patients['risk_category'] = df_patients.apply(classify_risk, axis=1)

print("Risk category distribution:")
display(df_patients['risk_category'].value_counts())

# Display a few patients with their assigned risk categories
print("\nSample patients with risk categories:")
display(df_patients[['patient_id', 'age', 'gender', 'blood_pressure_systolic', 'blood_pressure_diastolic', 'sugar_level_mg_dL', 'total_cholesterol_mg_dL', 'heart_rate_bpm', 'risk_category']].head())

"""### Identifying High-Risk Patients"""

high_risk_patients = df_patients[df_patients['risk_category'] == 'High Risk']
print(f"Number of high-risk patients: {len(high_risk_patients)}")
print("\nDetails of a few high-risk patients:")
display(high_risk_patients.head())

import pandas as pd
from faker import Faker
import random

# Initialize Faker
faker = Faker()

def generate_patient_record():
    gender = random.choice(['Male', 'Female'])
    age = random.randint(18, 90)

    # Realistic blood pressure values
    systolic = random.randint(90, 180)
    diastolic = random.randint(60, 120)

    # Realistic sugar levels (mg/dL)
    sugar_level = round(random.uniform(70.0, 200.0), 1)

    # Realistic cholesterol levels (mg/dL)
    total_cholesterol = random.randint(150, 280)
    hdl_cholesterol = random.randint(30, 80)
    ldl_cholesterol = random.randint(70, 190)

    # Realistic heart rate (beats per minute)
    heart_rate = random.randint(60, 100)

    return {
        'patient_id': faker.uuid4(),
        'age': age,
        'gender': gender,
        'blood_pressure_systolic': systolic,
        'blood_pressure_diastolic': diastolic,
        'sugar_level_mg_dL': sugar_level,
        'total_cholesterol_mg_dL': total_cholesterol,
        'hdl_cholesterol_mg_dL': hdl_cholesterol,
        'ldl_cholesterol_mg_dL': ldl_cholesterol,
        'heart_rate_bpm': heart_rate
    }

# Generate a large dataset (e.g., 10,000 records)
num_records = 10000
patient_data = [generate_patient_record() for _ in range(num_records)]

df_patients = pd.DataFrame(patient_data)

print(f"Generated dataset with {len(df_patients)} records.")
display(df_patients.head())
print(df_patients.info())

# Check for missing values
missing_values = df_patients.isnull().sum()
print("Missing values in each column:")
display(missing_values[missing_values > 0])

if missing_values.sum() == 0:
    print("\nNo missing values found in the dataset.")
else:
    print("\nMissing values found. Further action might be required.")

# Verify data types (already done with df_patients.info(), but explicitly confirm)
print("\nData types:")
display(df_patients.dtypes)

# Summary statistics for numerical columns to check ranges and potential outliers
display(df_patients.describe())

import matplotlib.pyplot as plt
import seaborn as sns

# Set style for plots
sns.set_style("whitegrid")

# Create subplots for numerical features distributions
fig, axes = plt.subplots(nrows=3, ncols=3, figsize=(18, 15))
axes = axes.flatten()

numerical_cols = ['age', 'blood_pressure_systolic', 'blood_pressure_diastolic',
                  'sugar_level_mg_dL', 'total_cholesterol_mg_dL',
                  'hdl_cholesterol_mg_dL', 'ldl_cholesterol_mg_dL', 'heart_rate_bpm']

for i, col in enumerate(numerical_cols):
    sns.histplot(df_patients[col], kde=True, ax=axes[i], color='skyblue')
    axes[i].set_title(f'Distribution of {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frequency')

# Remove any unused subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 5))
sns.countplot(x='gender', data=df_patients, palette='viridis')
plt.title('Distribution of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

print("\nDescriptive statistics for Blood Pressure (Systolic and Diastolic):")
display(df_patients[['blood_pressure_systolic', 'blood_pressure_diastolic']].describe())

print("\nDescriptive statistics for Sugar Levels:")
display(df_patients['sugar_level_mg_dL'].describe())

print("\nDescriptive statistics for Cholesterol Levels (Total, HDL, LDL):")
display(df_patients[['total_cholesterol_mg_dL', 'hdl_cholesterol_mg_dL', 'ldl_cholesterol_mg_dL']].describe())

print("\nDescriptive statistics for Heart Rate:")
display(df_patients['heart_rate_bpm'].describe())

fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(15, 12))
axes = axes.flatten()

health_metrics = [
    'blood_pressure_systolic', 'blood_pressure_diastolic',
    'sugar_level_mg_dL', 'heart_rate_bpm'
]

for i, col in enumerate(health_metrics):
    sns.boxplot(x='gender', y=col, data=df_patients, ax=axes[i], palette='coolwarm')
    axes[i].set_title(f'{col} by Gender')
    axes[i].set_xlabel('Gender')
    axes[i].set_ylabel(col)

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(18, 6))
axes = axes.flatten()

cholesterol_metrics = [
    'total_cholesterol_mg_dL', 'hdl_cholesterol_mg_dL', 'ldl_cholesterol_mg_dL'
]

for i, col in enumerate(cholesterol_metrics):
    sns.boxplot(x='gender', y=col, data=df_patients, ax=axes[i], palette='coolwarm')
    axes[i].set_title(f'{col} by Gender')
    axes[i].set_xlabel('Gender')
    axes[i].set_ylabel(col)

plt.tight_layout()
plt.show()

gender_stats = df_patients.groupby('gender')[numerical_cols].mean()
print("Average Health Metrics by Gender:")
display(gender_stats)

# Specific checks for numerical columns based on generation ranges

# Age: 18-90
age_outliers = df_patients[(df_patients['age'] < 18) | (df_patients['age'] > 90)]
print(f"\nAge values outside expected range (18-90): {len(age_outliers)}")

# Blood Pressure Systolic: 90-180, Diastolic: 60-120
bp_systolic_outliers = df_patients[(df_patients['blood_pressure_systolic'] < 90) | (df_patients['blood_pressure_systolic'] > 180)]
print(f"Blood Pressure Systolic values outside expected range (90-180): {len(bp_systolic_outliers)}")
bp_diastolic_outliers = df_patients[(df_patients['blood_pressure_diastolic'] < 60) | (df_patients['blood_pressure_diastolic'] > 120)]
print(f"Blood Pressure Diastolic values outside expected range (60-120): {len(bp_diastolic_outliers)}")

# Sugar Level: 70.0-200.0
sugar_outliers = df_patients[(df_patients['sugar_level_mg_dL'] < 70.0) | (df_patients['sugar_level_mg_dL'] > 200.0)]
print(f"Sugar Level values outside expected range (70.0-200.0): {len(sugar_outliers)}")

# Total Cholesterol: 150-280
total_chol_outliers = df_patients[(df_patients['total_cholesterol_mg_dL'] < 150) | (df_patients['total_cholesterol_mg_dL'] > 280)]
print(f"Total Cholesterol values outside expected range (150-280): {len(total_chol_outliers)}")

# HDL Cholesterol: 30-80
hdl_chol_outliers = df_patients[(df_patients['hdl_cholesterol_mg_dL'] < 30) | (df_patients['hdl_cholesterol_mg_dL'] > 80)]
print(f"HDL Cholesterol values outside expected range (30-80): {len(hdl_chol_outliers)}")

# LDL Cholesterol: 70-190
ldl_chol_outliers = df_patients[(df_patients['ldl_cholesterol_mg_dL'] < 70) | (df_patients['ldl_cholesterol_mg_dL'] > 190)]
print(f"LDL Cholesterol values outside expected range (70-190): {len(ldl_chol_outliers)}")

# Heart Rate: 60-100
heart_rate_outliers = df_patients[(df_patients['heart_rate_bpm'] < 60) | (df_patients['heart_rate_bpm'] > 100)]
print(f"Heart Rate values outside expected range (60-100): {len(heart_rate_outliers)}")